import { medicalText } from "./medical-form";
import type { ApplicationInput, ExtractedFields } from "./types";

const base: ExtractedFields = {
  patientName: "Mentor Example",
  policyNumber: "DEMO-1001",
  facilityName: "Example Family Clinic",
  providerCode: "CLINIC-01",
  department: "Family Medicine",
  serviceStart: "2026-08-12",
  chiefComplaint: "Routine health assessment",
  symptoms: "Routine wellness review",
  relevantMedicalHistory: "No known conditions or drug allergies.",
  physicalFindings: "Vital signs and examination normal.",
  investigations: "Not clinically indicated",
  testResults: "Not clinically indicated",
  treatment: "Routine wellness consultation",
  procedures: "Routine assessment",
  clinicalCourse: "Same-day visit completed with home recovery instructions.",
  diagnosis: "Routine health assessment",
  diagnosisCode: "Z00.0",
  supportingDocuments: "Consultation report and itemized bill",
  billingAmount: 100,
  eligibleAmount: 80,
  insurerPayment: 80,
  patientResponsibility: 20,
};
export const mentorApplication: ApplicationInput = {
  applicantName: "Mentor Example",
  age: 35,
  occupation: "Office worker",
  sumAssured: 100000,
  productLine: "Individual Life",
  medicalHistory: "No reported prior medical conditions.",
  disclosures: "No additional disclosures.",
  documents: [],
};
const surgical = {
  ...base,
  facilityName: "Example General Hospital",
  department: "General Surgery",
  serviceStart: "2026-08-12",
  serviceEnd: "2026-08-16",
  procedureDate: "2026-08-13",
  chiefComplaint: "Severe acute abdominal pain",
  symptoms: "Fever and tenderness",
  physicalFindings: "Abdominal guarding",
  investigations: "CT and ultrasound imaging",
  testResults: "Inflamed appendix",
  treatment: "Intravenous antibiotics and surgical care",
  procedures: "Appendectomy with operative report",
  clinicalCourse:
    "Multi-day admission; localized peritonitis complication monitored. Release after recovery.",
  diagnosis: "Acute appendicitis with localized peritonitis",
  diagnosisCode: "K35.30",
  supportingDocuments: "Operative report and hospital bill",
};
const dental = {
  ...base,
  facilityName: "Example Dental Center",
  department: "Dental",
  chiefComplaint: "Painful molar",
  symptoms: "Tooth sensitivity",
  physicalFindings: "Oral examination with percussion testing",
  investigations: "Periapical radiograph",
  testResults: "Pulp inflammation",
  treatment: "Root canal treatment",
  procedures: "Root canal and restoration",
  clinicalCourse: "Dental procedure completed.",
  diagnosis: "Pulpitis",
  diagnosisCode: "K04.0",
};
export const mentorScenarios = [
  {
    id: "clinic",
    title: "Complete clinic · STP",
    setting: "Outpatient wellness visit",
    fields: base,
    application: mentorApplication,
    expected: "ASSIGNED_STP",
  },
  {
    id: "surgery",
    title: "Complex surgery · specialist review",
    setting: "Formal inpatient admission",
    fields: surgical,
    application: { ...mentorApplication, age: 50, sumAssured: 600000 },
    expected: "ASSIGNED_MANUAL",
  },
  {
    id: "dental",
    title: "Dental · specialist review",
    setting: "Dental treatment",
    fields: dental,
    application: mentorApplication,
    expected: "ASSIGNED_MANUAL",
  },
  {
    id: "incomplete",
    title: "Missing diagnosis · Pool Queue",
    setting: "Outpatient consultation",
    fields: {
      ...base,
      diagnosis: "Not provided",
      diagnosisCode: "Not provided",
    },
    application: mentorApplication,
    expected: "POOL_QUEUE",
  },
  {
    id: "conflict",
    title: "Inpatient dental overlap · Pool Queue",
    setting: "Inpatient admission for tooth extraction",
    fields: { ...dental, procedures: "Tooth extraction" },
    application: mentorApplication,
    expected: "POOL_QUEUE",
  },
  {
    id: "contradiction",
    title: "Contradictory dates · Pool Queue",
    setting: "Formal inpatient admission",
    fields: { ...surgical, serviceEnd: "2026-08-10", eligibleAmount: 200 },
    application: mentorApplication,
    expected: "POOL_QUEUE",
  },
  {
    id: "capacity",
    title: "No eligible specialist · Pool Queue",
    setting: "Formal inpatient admission",
    fields: {
      ...surgical,
      diagnosis: "Acute appendicitis with myocardial infarction",
      diagnosisCode: "K35.30",
    },
    application: mentorApplication,
    expected: "POOL_QUEUE",
  },
].map((s) => ({ ...s, text: medicalText(s.fields, s.setting) }));
